version: "3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - c:/Users/pmaddu/Docker/DevworkFlow2/web:/app
  
  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules
      - c:/Users/pmaddu/Docker/DevworkFlow2/web:/app
    command :
      npm run test